version: "3"

services:
  frontend:
    build: frontend
    ports:
      - 8080:80
    networks:
      - net
    restart: always
    env_file:
      - .env

  backend:
    build: backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - net
    restart: always
    env_file:
      - .env

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - net
    restart: always

networks:
  net:
